"""Generate a single-agent control from only a request and the repository HEAD."""
from __future__ import annotations

from pathlib import Path

from .gitops import head
from .schema import Graph

SINGLE_INSTRUCTION = 'Keep the existing tests passing and add tests for the new behaviour.'


def single_graph(request: str, repo: Path, final_checks: list[str] | None = None) -> Graph:
    """No reference implementation, source inventory, planner or model is consulted.

    The repository basename is portable between experiment directories. With
    no supplied test command, only a generic Git whitespace check is scheduled;
    the agent still selects/runs tests as required by the request and goal.
    """
    if not request.strip():
        raise ValueError('request must not be empty')
    checks = list(final_checks or [])
    return Graph.model_validate({
        'request_id': 'single',
        'request': request,
        'repo': Path(repo).resolve().name,
        'base_commit': head(Path(repo)),
        'final_checks': checks,
        'generator': {'kind': 'manual'},
        'nodes': [{
            'id': 'solve',
            'title': 'Implement the whole request',
            'kind': 'implement',
            'goal': request + '\n\n' + SINGLE_INSTRUCTION,
            'edit_set': {'any_file': True, 'modify': [], 'create': []},
            'context_files': [], 'requires': [], 'requires_impl': [], 'provides': [],
            'check': {'commands': checks or ['git diff --check']},
        }],
        'edges': [],
        'revision_log': [{
            'action': 'other', 'nodes': ['solve'],
            'reason': 'Generated by the single command from the original request and repository HEAD.',
        }],
    })
